version: '3.9'

services:
  core_backend:
    build: ./core_backend
    ports:
      - "3000:3000"
    volumes:
      - ./core_backend/src:/usr/src/app/src
    command: npm run start:dev
    env_file:
      - ./.env
    depends_on:
      - redis
      - prometheus
    networks:
      - app_network

  postgres:
    image: postgres
    ports:
      - "5434:5432"
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
  
  redis:
    image: redis
    ports:
      - "6380:6379"
    networks:
      - app_network

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090" # Prometheus UI
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - app_network

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3001:3000" # Grafana UI
    env_file:
      - ./.env
      
    networks:
      - app_network
    depends_on:
      - prometheus

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
